// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDv6u01X61pyAzT0oyLHJ5uASF6Syt0zF4',
    appId: '1:805783725400:web:cdf3c64081e9e98018f12d',
    messagingSenderId: '805783725400',
    projectId: 'fir-b2caf',
    authDomain: 'fir-b2caf.firebaseapp.com',
    storageBucket: 'fir-b2caf.appspot.com',
    measurementId: 'G-W15GE5583F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfTuBwy4S-CKVEs2VOGuYbwKtRp9RMUrg',
    appId: '1:805783725400:android:ff2d85fcf520e85e18f12d',
    messagingSenderId: '805783725400',
    projectId: 'fir-b2caf',
    storageBucket: 'fir-b2caf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDioPKkDAHkOQtFEzIzDqggxf66Ic37NLU',
    appId: '1:805783725400:ios:955724e345a6b6eb18f12d',
    messagingSenderId: '805783725400',
    projectId: 'fir-b2caf',
    storageBucket: 'fir-b2caf.appspot.com',
    iosBundleId: 'com.example.examinator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDioPKkDAHkOQtFEzIzDqggxf66Ic37NLU',
    appId: '1:805783725400:ios:955724e345a6b6eb18f12d',
    messagingSenderId: '805783725400',
    projectId: 'fir-b2caf',
    storageBucket: 'fir-b2caf.appspot.com',
    iosBundleId: 'com.example.examinator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDv6u01X61pyAzT0oyLHJ5uASF6Syt0zF4',
    appId: '1:805783725400:web:398121f083fd73ff18f12d',
    messagingSenderId: '805783725400',
    projectId: 'fir-b2caf',
    authDomain: 'fir-b2caf.firebaseapp.com',
    storageBucket: 'fir-b2caf.appspot.com',
    measurementId: 'G-B47HVJL8BR',
  );

}